# DEPRECATED: GlobalAccount is deprecated and will be removed in a future release. Use globalaccount reference in providerconfig to specify your GlobalAccount instead.

apiVersion: account.btp.sap.crossplane.io/v1alpha1
kind: GlobalAccount
metadata:
  annotations:
    crossplane.io/external-name: SAP Cloud Orchestration Canary
  name: co-ga-canary
spec:
  providerConfigRef:
    name: default
