---
name: bump version
on:
  repository_dispatch:
    types: [ bump-version-command ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  generate:
    uses: cloud-orchestration/.workflows/.github/workflows/bump-version.yaml@v1.16.7
    secrets: inherit
