name: make reviewable

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}


env:
  # Common versions
  GO_VERSION: '1.21'
jobs:
  reviewable:
    uses: cloud-orchestration/.workflows/.github/workflows/make-reviewable.yml@v1.16.7
    secrets: inherit

